development:
  dialect: postgres
  database: ai_development
  user: {{env "DATABASE_USER"}}
  password: {{env "DATABASE_PASSWORD"}}
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: ai_test
  user: postgres  
  password: password
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ai_production?sslmode=disable"}}